### ISSUE TITLE
Unforseen Error when logging in -- Nylas Mail 1.0.11

### ISSUE THREAD

**Issue by danilogcarolino** [nylas/nylas-mail#3211]
Nylas Mail cannot connect to the Gmail account and displays the error message - mac app:
"Sorry, we had trouble logging you in" 

However the site displays: "You're all set!"

##### What operating system are you using?
macOS 10.12.2

##### What version of N1 are you using?
Nylas Mail 1.0.11 (1.0.11)

##### Do you have any third-party plugins installed? If so, which ones?
Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

Debug log: 

nylas-env.coffee:270APIError: Please contact support@nylas.com. An unforeseen error has occurred.
    at new APIError (/src/flux/errors.es6:28:19)
    at _priorityUiCoordinator2.default.settle.then (/src/flux/nylas-api-request.es6:177:30)
From previous event:
    at NylasAPIRequest.run (/src/flux/nylas-api-request.es6:152:12)
    at Object.<anonymous> (/internal_packages/onboarding/lib/onboarding-helpers.es6:71:40)
    at next (<anonymous>)
    at step (/internal_packages/onboarding/lib/onboarding-helpers.es6:4:1)
    at /internal_packages/onboarding/lib/onboarding-helpers.es6:4:1
From previous event:
    at Object.<anonymous> (/internal_packages/onboarding/lib/onboarding-helpers.es6:4:1)
    at Object.authIMAPForGmail [as accountFromTokenFn] (/Applications/Nylas Mail.app/Contents/Resources/app.asar/internal_packages/onboarding/lib/onboarding-helpers.js:54:18)
    at /src/components/oauth-signin-page.jsx:124:44
    at next (<anonymous>)
    at step (/src/components/oauth-signin-page.jsx:4:1)
    at /src/components/oauth-signin-page.jsx:4:1
From previous event:
    at /src/components/oauth-signin-page.jsx:4:1
    at OAuthSignInPage.fetchAccountDataWithToken (/src/components/oauth-signin-page.jsx:121:46)
    at /src/components/oauth-signin-page.jsx:105:14
    at next (<anonymous>)
    at step (/src/components/oauth-signin-page.jsx:4:1)
    at /src/components/oauth-signin-page.jsx:4:1
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at step (/src/components/oauth-signin-page.jsx:4:1)
    at /src/components/oauth-signin-page.jsx:4:1
From previous event:
    at /src/components/oauth-signin-page.jsx:4:1
    at poll (/src/components/oauth-signin-page.jsx:100:5) ObjectpluginIds: Array[1]__proto__: Objectmodule.exports.NylasEnvConstructor.reportError @ nylas-env.coffee:270

**Comment by yannick-mamudo** [comment]
#3179

**Comment by jstejada** [comment]
hi @danilogcarolino thanks for the report! We are looking into it

**Comment by danilogcarolino** [comment]
@jstejada ok. One note: this only happens in Nylas Mail, Nylas N1 continues to function normally.

**Comment by jstejada** [comment]
hi @danilogcarolino , is this still happening on version 1.0.15? thanks!

**Comment by danilogcarolino** [comment]
Hey, @jstejada. I updated to 1.0.17 and still can not access unfortunately. I've tried everything.

**Comment by danilogcarolino** [comment]
@jstejada Detail: I tested with an alternative Gmail account (which had not added yet) and it worked. Apparently the problem is with account data.

**Comment by danilogcarolino** [comment]
Oh, I used Pro and Mail simultaneously (to test). That must have complicated things.

**Comment by jstejada** [comment]
@danilogcarolino are you still seeing issues on version 1.0.15? If so, feel free to reopen this issue!

**Comment by danilogcarolino** [comment]
Yes. The account I used in Pro and Mail still does not work.
