### ISSUE TITLE
Folder mapping failure: No Trash/Sent - Can't Save to Sent or Delete Messages

### ISSUE THREAD

**Issue by nomad1988** [nylas/nylas-mail#3212]
I first notice this because I was unable to send messages with my iCloud account (as reported here #3182 ). Additionally I was unable to delete any of the messages in my iCloud account either. Then I noticed that iCloud Trash and Sent folders are missing on the sidebar under "All Accounts" portion, whereas other iCloud folders such as Draft are there. See below: 

<img width="249" alt="screen shot 2017-01-23 at 7 44 37 pm" src="https://cloud.githubusercontent.com/assets/6695603/22229370/481169aa-e1a5-11e6-8d72-7732af0dc578.png">

If I scroll al the way down the folders are listed under iCloud but they somehow don't seem to be "linked" to their intended functions.
<img width="251" alt="screen shot 2017-01-23 at 7 52 24 pm" src="https://cloud.githubusercontent.com/assets/6695603/22229492/0303b862-e1a6-11e6-8c28-51f52e0c06d0.png">

 

##### Are there any related issues?

Yes: #3182 

##### What operating system are you using?

Mac OS X Sierra Version 10.12.2

##### What version of N1 are you using?

Version 1.0.11

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

The 6 that come default with N1 1.0.11

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

iCloud

**Comment by jstejada** [comment]
thanks for the report @nomad1988 , we are going to look into it!

**Comment by monkeydri** [comment]
Same problem with custom IMAP account. I have many of them, problem appears only for one of those accounts (OVH IMAP account).

Nylas Mail v1.0.29 - macOS Sierra 10.12.3

**Comment by monkeydri** [comment]
problem still there with Nylas Mail v1.0.30

**Comment by n3oxmind** [comment]
Getting this error from Nylas Mail v1.0.30
 at new APIError (/src/flux/errors.es6:29:19)
    at _priorityUiCoordinator2.default.settle.then (/src/flux/nylas-api-request.es6:176:30)
    at tryCatcher (/home/n30x/Downloads/nylas-mail-1.0.30/dist/nylas-linux-x64/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/n30x/Downloads/nylas-mail-1.0.30/dist/nylas-linux-x64/resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/n30x/Downloads/nylas-mail-1.0.30/dist/nylas-linux-x64/resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/home/n30x/Downloads/nylas-mail-1.0.30/dist/nylas-linux-x64/resources/app.asar/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/home/n30x/Downloads/nylas-mail-1.0.30/dist/nylas-linux-x64/resources/app.asar/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/n30x/Downloads/nylas-mail-1.0.30/dist/nylas-linux-x64/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/n30x/Downloads/nylas-mail-1.0.30/dist/nylas-linux-x64/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

Sorry, we had trouble logging you in 
connect ECONNREFUSED 127.0.0.1:2578
Please try again. If you continue to see this error contact support@nylas.com
Page didn't open? Paste this URL into your browser:

**Comment by monkeydri** [comment]
problem still there with Nylas Mail v1.0.45...

**Comment by monkeydri** [comment]
With Nylas v2.0.14 mail cannot even be sent anymore, total failure.

Sorry but I'm getting tired if reporting error logs as no one seems to go through them.

**Comment by tomkeysers** [comment]
On Nylas v2.0.15 with a custom IMAP account - I can now send emails buy get an error which says that the 'Sent' folder can't be found and email aren't saved... Still not good enough.

**Comment by jstejada** [comment]
thanks for the info. merging into duplicate issue #1457
