### ISSUE TITLE
Ubuntu: Error: connect ECONNREFUSED 127.0.0.1:2578

### ISSUE THREAD

**Issue by anidotnet** [nylas/nylas-mail#3270]
##### What operating system are you using?
Ubuntu 16.04 LTS 64bit

##### What version of Nylas Mail are you using?
nylas-1.0.21 (built from master)

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
While adding Gmail, after authenticating successfully with Gmail, I am getting below error message

Error: connect ECONNREFUSED 127.0.0.1:2578

NOTE: I built nylas taking the code form master. While running with "npm start" I am getting below error in console

```
[16300:0207/111747:INFO:CONSOLE(110)] "Thread Search: Index built successfully in 0.063s", source: /media/anindya/data/codebase/nylas-mail/internal_packages/search-index/lib/thread-search-index-store.es6 (110)
[16300:0207/111759:INFO:CONSOLE(318)] "APIError: Error: connect ECONNREFUSED 127.0.0.1:2578
    at new APIError (errors.es6:29:19)
    at _priorityUiCoordinator2.default.settle.then (nylas-api-request.es6:177:30)
From previous event:
    at NylasAPIRequest.run (nylas-api-request.es6:152:12)
    at Object.<anonymous> (onboarding-helpers.es6:72:40)
    at next (<anonymous>)
    at step (onboarding-helpers.es6:5:1)
From previous event:
    at Object.<anonymous> (onboarding-helpers.es6:5:1)
    at oauth-signin-page.jsx:124:44
    at next (<anonymous>)
    at step (oauth-signin-page.jsx:4:1)
From previous event:
    at oauth-signin-page.jsx:4:1
    at oauth-signin-page.jsx:105:14
    at next (<anonymous>)
    at step (oauth-signin-page.jsx:4:1)
    at oauth-signin-page.jsx:4:1
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at oauth-signin-page.jsx:4:1", source: /media/anindya/data/codebase/nylas-mail/src/nylas-env.coffee (318)
APIError: Error: connect ECONNREFUSED 127.0.0.1:2578
    at new APIError (errors.es6:29:19)
    at _priorityUiCoordinator2.default.settle.then (nylas-api-request.es6:177:30)
From previous event:
    at NylasAPIRequest.run (nylas-api-request.es6:152:12)
    at Object.<anonymous> (onboarding-helpers.es6:72:40)
    at next (<anonymous>)
    at step (onboarding-helpers.es6:5:1)
From previous event:
    at Object.<anonymous> (onboarding-helpers.es6:5:1)
    at oauth-signin-page.jsx:124:44
    at next (<anonymous>)
    at step (oauth-signin-page.jsx:4:1)
From previous event:
    at oauth-signin-page.jsx:4:1
    at oauth-signin-page.jsx:105:14
    at next (<anonymous>)
    at step (oauth-signin-page.jsx:4:1)
    at oauth-signin-page.jsx:4:1
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at oauth-signin-page.jsx:4:1

```

**Comment by colinking** [comment]
+1. I'm also getting this error (when building from master), but on Mac OS X 10.12.3.

**Comment by colinking** [comment]
From @jstejada:

> Unfortunately you can’t currently run Nylas Mail from source (unless it’s Nylas Pro `n1-pro` branch). Our core sync code isn’t open source yet and it’s included in a private submodule, so when you clone nylas-mail you wont have access to this private code necessary to run the app in dev mode

**Comment by anidotnet** [comment]
Damn! Hope they will open source it soon.

**Comment by bithooked** [comment]
I hate to be a pain, but aren't you violating the GPL by distributing under the GPL with a non-GPL dependency?

**Comment by anidotnet** [comment]
So the obvious question now is when can we expect it to be available? Linux build or the private repo to be open sourced?
