### ISSUE TITLE
[KDE Neon] Can't build Nylas N1

### ISSUE THREAD

**Issue by AbsyntheSyne** [nylas/nylas-mail#3276]
##### Are there any related issues?

Couldn't find anything

##### What operating system are you using?
KDE Neon User Edition 5.9, based on Ubuntu 16.04 LTS

##### What version of Nylas Mail are you using?
Whatever the master version is

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Nope

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Nope

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Nope

I can't build Nylas N1. every time I cd into the directory and do script/bootstrap it fails with this error message

/home/emily/nylas-mail/script/bootstrap:23
  const {cwd, env} = Object.assign({cwd: '.', env: 'system'}, options);
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by rage28** [comment]
I'm on KDE neon 16.04 as well but am able to compile (although it still does not work due to #3270 ). What nodejs version are you using? I'm on 6.9.5
