### ISSUE TITLE
Error compiling N1, Arch Linux

### ISSUE THREAD

**Issue by thymbahutymba** [nylas/nylas-mail#3285]
##### Are there any related issues?

...

##### What operating system are you using?
Arch Linux
##### What version of Nylas Mail are you using?
Version in AUR repository, n1-git 0.4.32.r987.gf35008d-1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

atom-package-manager@1.1.1 install /tmp/yaourt-tmp-andrea/aur-n1-git/src/N1/apm/node_modules/atom-package-manager
node ./script/download-node.js

module.js:472
    throw err;
    ^

Error: Cannot find module '../src/request'
  at Function.Module._resolveFilename (module.js:470:15)
  at Function.Module._load (module.js:418:25)
  at Module.require (module.js:498:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/tmp/yaourt-tmp-andrea/aur-n1-git/src/N1/apm/node_modules/atom-package-manager/script/download-node.js:16:13)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.runMain (module.js:605:10)
  at run (bootstrap_node.js:418:7)
  at startup (bootstrap_node.js:139:9)
  at bootstrap_node.js:533:3

n1-bundled-apm@ /tmp/yaourt-tmp-andrea/aur-n1-git/src/N1/apm
└── d@0.1.1  extraneous

npm WARN n1-bundled-apm@ No license field.
npm ERR! Linux 4.9.8-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! atom-package-manager@1.1.1 install: `node ./script/download-node.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-package-manager@1.1.1 install script 'node ./script/download-node.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-package-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./script/download-node.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-package-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-package-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/andrea/.npm/_logs/2017-02-13T15_47_15_192Z-debug.log
==> ERRORE: Si è verificato un errore in build().
    L'operazione sta per essere interrotta...

$ cat  /home/andrea/.npm/_logs/2017-02-13T15_47_15_192Z-debug.log :
30729 verbose stack Error: atom-package-manager@1.1.1 install: `node ./script/download-node.js`
30729 verbose stack Exit status 1
30729 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
30729 verbose stack     at emitTwo (events.js:106:13)
30729 verbose stack     at EventEmitter.emit (events.js:192:7)
30729 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
30729 verbose stack     at emitTwo (events.js:106:13)
30729 verbose stack     at ChildProcess.emit (events.js:192:7)
30729 verbose stack     at maybeClose (internal/child_process.js:890:16)
30729 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
30730 verbose pkgid atom-package-manager@1.1.1
30731 verbose cwd /tmp/yaourt-tmp-andrea/aur-n1-git/src/N1/apm
30732 error Linux 4.9.8-1-ARCH
30733 error argv "/usr/bin/node" "/usr/bin/npm" "install"
30734 error node v7.5.0
30735 error npm  v4.2.0
30736 error code ELIFECYCLE
30737 error errno 1
30738 error atom-package-manager@1.1.1 install: `node ./script/download-node.js`
30738 error Exit status 1
30739 error Failed at the atom-package-manager@1.1.1 install script 'node ./script/download-node.js'.
30739 error Make sure you have the latest version of node.js and npm installed.
30739 error If you do, this is most likely a problem with the atom-package-manager package,
30739 error not with npm itself.
30739 error Tell the author that this fails on your system:
30739 error     node ./script/download-node.js
30739 error You can get information on how to open an issue for this project with:
30739 error     npm bugs atom-package-manager
30739 error Or if that isn't available, you can get their info via:
30739 error     npm owner ls atom-package-manager
30739 error There is likely additional logging output above.
30740 verbose exit [ 1, true ]

**Comment by ArchangeGabriel** [comment]
You should have posted this on AUR. The reason is that the AUR package isn’t up-to-date, the source URL should now be `git+https://github.com/nylas/nylas-mail.git#branch=n1-pro` (not exactly sure about the syntax, also maybe `git+https://github.com/nylas/nylas-mail/tree/n1-pro` could work).

**Comment by thymbahutymba** [comment]
I'm trying to build myself with dowload nylas-mail from git, i have the same error!

**Comment by ArchangeGabriel** [comment]
Did you make use of the `n1-pro` branch? That’s the import part, the repo name is mostly cosmetic (the old one redirects to the new one anyway). Current master branch is nylas-mail, which in contrary to n1 isn’t buildable yet.

**Comment by thymbahutymba** [comment]
Isn't better clone master branch? I'm trying to compile n1-pro now, but i need to understand why you tell me to clone n1-pro and not master branch.

**Comment by ArchangeGabriel** [comment]
For master vs n1-pro branch, please read this: https://github.com/nylas/nylas-mail/issues/3256#issuecomment-277445597. `master` branch is Nylas Mail, while `n1-pro` is Nylas N1.

Can’t help you for the n1-pro branch, maybe look if other issues are open regarding compilation of n1-pro, else update this one. Tell exactly what you did (and obviously that implies running the build command directly rather than through the PKGBUILD), and maybe the devs will be able to see what’s going wrong.
