### ISSUE TITLE
I can't loging in any e-mail service after building to windows

### ISSUE THREAD

**Issue by daviwesley** [nylas/nylas-mail#3295]
I am using the latest version of nylas.

SCAN TABLE Category for SELECT `Category`.`data` FROM `Category`   
nylas://nylas-private-fonts/fonts/Nylas-Pro-Thin.otf Failed to load resource: net::ERR_FILE_NOT_FOUND
nylas://nylas-private-fonts/fonts/Nylas-Pro-Blond.otf Failed to load resource: net::ERR_FILE_NOT_FOUND
nylas://nylas-private-fonts/fonts/Nylas-Pro-Normal.otf Failed to load resource: net::ERR_FILE_NOT_FOUND
/C:/Users/Davi%20Wesley/Documents/Electron%20Projects/nylas-mail/src/nylas-env.coffee:312 APIError: connect ECONNREFUSED 127.0.0.1:1337
    at new APIError (errors.es6:29:19)
    at _priorityUiCoordinator2.default.settle.then (nylas-api-request.es6:176:30)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at NylasAPIRequest.run (nylas-api-request.es6:151:12)
    at Object.<anonymous> (onboarding-helpers.es6:72:40)
    at next (<anonymous>)
    at step (onboarding-helpers.es6:5:1)
From previous event:
    at Object.<anonymous> (onboarding-helpers.es6:5:1)
    at oauth-signin-page.jsx:124:44
    at next (<anonymous>)
    at step (oauth-signin-page.jsx:4:1)
From previous event:
    at oauth-signin-page.jsx:4:1
    at oauth-signin-page.jsx:105:14
    at next (<anonymous>)
    at step (oauth-signin-page.jsx:4:1)
    at oauth-signin-page.jsx:4:1
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at oauth-signin-page.jsx:4:1 Objectmodule.exports.NylasEnvConstructor.reportError @ /C:/Users/Davi%20Wesley/Documents/Electron%20Projects/nylas-mail/src/nylas-env.coffee:312
/C:/Users/Davi%20Wesley/Documents/Electron%20Projects/nylas-mail/src/nylas-env.coffee:312 APIError: connect ECONNREFUSED 127.0.0.1:1337
    at new APIError (errors.es6:29:19)
    at _priorityUiCoordinator2.default.settle.then (nylas-api-request.es6:176:30)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at NylasAPIRequest.run (nylas-api-request.es6:151:12)
    at Object.<anonymous> (onboarding-helpers.es6:72:40)
    at next (<anonymous>)
    at step (onboarding-helpers.es6:5:1)
From previous event:
    at Object.<anonymous> (onboarding-helpers.es6:5:1)
    at oauth-signin-page.jsx:124:44
    at next (<anonymous>)
    at step (oauth-signin-page.jsx:4:1)
From previous event:
    at oauth-signin-page.jsx:4:1
    at oauth-signin-page.jsx:105:14
    at next (<anonymous>)
    at step (oauth-signin-page.jsx:4:1)
    at oauth-signin-page.jsx:4:1
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at oauth-signin-page.jsx:4:1 Objectmodule.exports.NylasEnvConstructor.reportError @ /C:/Users/Davi%20Wesley/Documents/Electron%20Projects/nylas-mail/src/nylas-env.coffee:312

**Comment by KyleKing** [comment]
Nylas Mail can't be built from source yet. One of the submodules hasn't been open sourced yet, see https://github.com/nylas/nylas-mail/issues/3244#issuecomment-276533373
