### ISSUE TITLE
Auth token missing for account

### ISSUE THREAD

**Issue by danielmelogpi** [nylas/nylas-mail#3332]
```
Auth token missing for accountError: Auth token missing for account
    at NylasAPIRequest._defaultAuth (/src/flux/nylas-api-request.es6:179:15)
    at /src/flux/nylas-api-request.es6:45:53
    at next (<anonymous>)
    at step (/src/flux/nylas-api-request.es6:7:1)
    at Promise._execute (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:77:14)
    at /src/flux/nylas-api-request.es6:7:1
    at /src/flux/syncback-task-api-request.es6:72:53
    at next (<anonymous>)
    at step (/src/flux/syncback-task-api-request.es6:6:1)
    at Promise._execute (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:77:14)
    at /src/flux/syncback-task-api-request.es6:6:1
    at Promise._execute (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:77:14)
    at SyncbackTaskAPIRequest.run (/src/flux/syncback-task-api-request.es6:70:12)
    at SendDraftTask.<anonymous> (/src/flux/tasks/send-draft-task.es6:124:33)
    at next (<anonymous>)
    at step (/src/flux/tasks/send-draft-task.es6:15:1)
    at Promise._execute (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:77:14)
    at SendDraftTask._sendWithSingleBody (/src/flux/tasks/send-draft-task.es6:15:1)
    at /src/flux/tasks/send-draft-task.es6:93:18
    at next (<anonymous>)
    at step (/src/flux/tasks/send-draft-task.es6:15:1)
    at Promise._execute (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:77:14)
    at /src/flux/tasks/send-draft-task.es6:15:1
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)APIError: Auth token missing for account
    at new APIError (/src/flux/errors.es6:28:19)
    at NylasAPIRequest._defaultAuth (/src/flux/nylas-api-request.es6:188:13)
    at /src/flux/nylas-api-request.es6:45:53
    at next (<anonymous>)
    at step (/src/flux/nylas-api-request.es6:7:1)
    at /src/flux/nylas-api-request.es6:7:1
    at /src/flux/syncback-task-api-request.es6:72:53
    at next (<anonymous>)
    at step (/src/flux/syncback-task-api-request.es6:6:1)
From previous event:
    at /src/flux/syncback-task-api-request.es6:6:1
From previous event:
    at SyncbackTaskAPIRequest.run (/src/flux/syncback-task-api-request.es6:70:12)
    at SendDraftTask.<anonymous> (/src/flux/tasks/send-draft-task.es6:124:33)
    at next (<anonymous>)
    at step (/src/flux/tasks/send-draft-task.es6:15:1)
From previous event:
    at SendDraftTask._sendWithSingleBody (/src/flux/tasks/send-draft-task.es6:15:1)
    at /src/flux/tasks/send-draft-task.es6:93:18
    at next (<anonymous>)
    at step (/src/flux/tasks/send-draft-task.es6:15:1)
From previous event:
    at /src/flux/tasks/send-draft-task.es6:15:1
From previous event:
    at SendDraftTask.performRemote (/src/flux/tasks/send-draft-task.es6:46:6)
    at SendDraftTask.runRemote (/src/flux/tasks/task.es6:230:19)
    at TaskQueue._processTask (/src/flux/stores/task-queue.coffee:258:10)
    at TaskQueue._processTask (/src/flux/stores/task-queue.coffee:1:1)
    at TaskQueue._processQueue (/src/flux/stores/task-queue.coffee:222:8)
    at TaskQueue._processQueue (/src/flux/stores/task-queue.coffee:1:1)
    at /src/flux/stores/task-queue.coffee:372:10
    at /Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/underscore/underscore.js:768:19
```
##### Are there any related issues?
I found this problem on a closed issue. Somebody pointed out that the relase 0.4.x solver the issue. Unfortunately I'm using a much more recent version...

##### What operating system are you using?
Mac OS

##### What version of Nylas Mail are you using?
1.0.39

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only have this problem with one account.
The email provider is mail.totvs.com.br.
I can fetch the e-mails and I receive a notification when new messages arrive but I'm unable to have outgoing e-mail to work.

The server configuration is like this:

````
Configuração POP
Nome do servidor: mail.totvs.com.br
Porta: 995
Método de criptografia: SSL



Configuração IMAP
Nome do servidor: mail.totvs.com.br
Porta: 993
Método de criptografia: SSL



Configuração SMTP
Nome do servidor: mail.totvs.com.br
Porta: 587
Método de criptografia: TLS

````

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Any e-mail using the provider above yields the error

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
This is a bug

**Comment by danielmelogpi** [comment]
Sometimes I alse see the erros below. Not sure if it's associated but it also happens in the account mentioned above.


````
Cannot read property 'host' of undefinedTypeError: Cannot read property 'host' of undefined
    at sendmail-client.es6:20:24
    at throw (<anonymous>)
    at step (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/isomorphic-core/src/sendmail-client.es6:3:191)
    at /Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/isomorphic-core/src/sendmail-client.es6:3:402
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)Error
    at new APIError (/src/flux/errors.es6:28:19)
    at _actions2.default.didReceiveSyncbackRequestDeltas.listen.syncbackRequests (/src/flux/syncback-task-api-request.es6:30:25)
    at EventEmitter.eventHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Function.functor [as didReceiveSyncbackRequestDeltas] (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at DeltaProcessor._notifyOfSyncbackRequestDeltas (/src/services/delta-processor.es6:139:13)
    at /src/services/delta-processor.es6:77:12
    at next (<anonymous>)
    at step (/Applications/Nylas Mail.app/Contents/Resources/app.asar/src/services/delta-processor.js:35:191)
    at /Applications/Nylas Mail.app/Contents/Resources/app.asar/src/services/delta-processor.js:35:361
    at tryCatcher (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Applications/Nylas Mail.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
````

**Comment by danielmelogpi** [comment]
Is anyone still taking care of this repository?

**Comment by sachinag** [comment]
We have known sent mail issues with providers not explicitly listed in our onboarding.  We're working on it!  Closing as this is just one provider.

**Comment by danielmelogpi** [comment]
It seems that the security configuration is differente between the imap and smtp servers. The checkbox to set that doesn't allow this differentece, always picking up the last one modified and applying to both.

Could it be a suggestion to allow for different uses of ssl and tls on the configuration view?

**Comment by sachinag** [comment]
@spang is working on the superset of these issues.  Thanks!

**Comment by behzadsh** [comment]
I have the same issue with other providers that use SSL for IMAP and TLS for SMTP

**Comment by ale93p** [comment]
Same issue with the custom IMAP address of my university

**Comment by Konzertheld** [comment]
Same issue with a self-hosted postfix / dovecot mail server.
