### ISSUE TITLE
Nylas Mail can't start: Error: SQLite: database disk image is malformed

### ISSUE THREAD

**Issue by mollierobbert** [nylas/nylas-mail#3343]
Nylas is starting, but not showing up on macOS 10.12.3.

It has been working fine for about a week. I've recently installed a Nylas update, but I'm not sure if that's related.

I tried reinstalling from the .dmg download at Nylas.com, but to no avail.

##### Are there any related issues?
It's the exact same as #2778, but on macOS.

##### What operating system are you using?
macOS 10.12.3

##### What version of Nylas Mail are you using?
1.0.48

##### Do you have any third-party plugins installed? If so, which ones?
None.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
The app simply won't open.

**Comment by mollierobbert** [comment]
I think macOS has corrupted a Nylas db file when macOS crashed earlier today. When I start Nylas, I get the following output in Console:

```
Mar 30 18:57:44 M84803 Nylas Mail[1280]: Streaming log data to /var/folders/96/yzxs4d0n2f9gzs7bv243qqmh0000gp/T/Nylas-Mail-1280.log
Mar 30 18:57:44 M84803 Nylas Mail[1280]: App load time: 336ms
Mar 30 18:57:44 M84803 Nylas Mail[1280]: Error: SQLite: database disk image is malformed
	    at Error (native)
	    at Database.db.on (/src/database-helpers.es6:12:10)
	    at emitNone (events.js:86:13)
	    at Database.emit (events.js:185:7) {}
...
```

**Comment by mollierobbert** [comment]
Removing `~/.nylas-mail` solved the issue, although I've lost all configuration in the process.

**Comment by hsin421** [comment]
Same issue here.

**Comment by brandonmbanks** [comment]
I had this same problem. I also had to remove `~/.nylas-mail`

**Comment by jadengore** [comment]
Also have this issue, don't want to lose my configuration so I'm going to wait for a fix.

**Comment by brandonmbanks** [comment]
Seems to be a common problem on my Mac right now.

**Comment by hsin421** [comment]
was waiting for a fix for some time; then gave up and deleted `~/.nylas-mail` and reconfigured

**Comment by chris-downs** [comment]
Same issue here as well. OSX 10.12.4 crashed in its sleep and the DB is corrupt.

**Comment by ajpiano** [comment]
Ditto, same thing here. Had to nuke `~/.nylas-mail` - luckily I only have two accounts to reconfigure...

**Comment by kleinsch** [comment]
Same. Not super excited about leaving my laptop on for 3 days to sync 17G of emails. Nylas needing to sync all your email is rough to begin with, but if it has to do that again when it crashes? Gonna lose users.

**Comment by jstejada** [comment]
Thanks for the report everyone! We're going to look into this!

**Comment by peixotorms** [comment]
Hi, is this the reason why,  I installed this a couple of hours ago on Windows 10, but my .sqlite files keep hammering the disk?

I have 4 accounts, the .sqlite files keep growing...
http://pasteboard.co/4dvL5q2yl.png

If this is synchronizing all mail that is just wrong. Several mail clients give you the option to do this for the last 2 weeks, 1 month, 3 months, a year, etc... even windows mail app (which is crap).

Should I be worried about the ever growing .sqlite files and disk usage?

**Comment by djungelkraem** [comment]
Same behavior.
Tried downgrading as well since I thought it was the upgrade from ver 1.x.x to 2.x.x upgrade that caused the problem. Nothing.

Deleted `~/.nylas-mail` and Im up and running again.

**Comment by jstejada** [comment]
Hi all! These issues should be fixed in version 2.0.15 (it should correctly inform you that the database is corrupted and rebuild it).

Let me know if you continue having issues!

**Comment by kvacquier** [comment]
Got it on the last version
2017-04-19 08:42:31.411 Nylas Mail[814:18675] Streaming log data to /var/folders/d_/21j44nrx6v5ctgs7v_8xpx8r0000gp/T/Nylas-Mail-814.log
2017-04-19 08:42:31.594 Nylas Mail[814:18675] App load time: 326ms
2017-04-19 08:42:31.624 Nylas Mail[814:18675] Error: SQLite: database disk image is malformed
    at Error (native)
    at Database.<anonymous> (/src/database-helpers.es6:39:12)
    at emitNone (events.js:86:13)
    at Database.emit (events.js:185:7) {}

**Comment by jstejada** [comment]
Hi @kvacquier , are you sure this is version 2.0.15?

**Comment by kvacquier** [comment]
Yes : Version 2.0.15 (2.0.15)
Updated yesterday (after the reception of the email) and crashed this morning

**Comment by jstejada** [comment]
Thanks! So the app doesn't start at all, correct? Do you see a dialog like this one at any point?

![image](https://cloud.githubusercontent.com/assets/1271509/25193826/394687d0-24ed-11e7-80a9-51eff83fd661.png)

**Comment by jstejada** [comment]
(FYI as a temporary solution you can just delete `~/.nylas-mail/edgehill.db` instead of having to delete the whole folder `.nylas-mail` folder)

**Comment by kvacquier** [comment]
i don't have problems anymore. But i didn't get the the pop-up last time

**Comment by dete** [comment]
@jstejada: I just had this same issue with 2.0.32. Deleting `edgehill.db` fixed it.

Symptoms were:
 - App would launch, but menu bar would show only File->Quit. No windows.
 - Console indicated a SQLite format error.
 - Deleting `edgehill.db` in Terminal got me back to the login screen

<details>
<summary>Log Entry</summary>

```
Jun 29 14:14:22 Diorama Nylas Mail[31180]: Error: SQLite: database disk image is malformed
	    at Error (native)
	    at Database.<anonymous> (/src/database-helpers.es6:39:12)
	    at emitNone (events.js:86:13)
	    at Database.emit (events.js:185:7) {}

```
</details>

<details>
<summary>Computer Info</summary>

```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro13,3
  Processor Name:	Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB

  System Version:	macOS 10.12.5 (16F73)
  Kernel Version:	Darwin 16.6.0
```
</details>

**Comment by JesseObrien** [comment]
Can confirm I got this error on version 2.0.32 today. Deleting `edgehill.db` fixed it as well.

**Comment by smdahmed** [comment]
Seeing this issue with 2.0.32. I did try to delete the edgehill.db but of no use.

![image](https://user-images.githubusercontent.com/6824174/31474191-1e08097e-aef1-11e7-865e-fe203e1e0db7.png)
