### ISSUE TITLE
Bug: N1 for windows spontaneous update to Nylas Mail: 'Cannot find module 'isomorphic-core''

### ISSUE THREAD

**Issue by wgoodall01** [nylas/nylas-mail#3366]
##### Are there any related issues?
Not that I can find, no.

##### What operating system are you using?
Windows 10:
```batch
C:\Users\me>ver
Microsoft Windows [Version 10.0.14393]
```

##### What version of Nylas Mail are you using?
2.0.10

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
N/A

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
N/A
##### Is the issue reproducible with a particular attachment, message, signature, etc?
N/A

Nylas N1 (the latest Windows build) appears to have updated itself to Nylas Mail, and now refuses to start. In the `AppData/Local/nylas` folder, the app is now launching from `app-2.0.10` instead of `app-1.5.0` (which is still there). When it launched, it opens 3 instances of itself, and in each, opens the dev console immediately, displaying the following error:

```
index.js:28 Error: Cannot find module 'isomorphic-core'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\user\AppData\Local\nylas\app-2.0.10\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/src\module-cache.coffee:267:20)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/src\flux\stores\database-store.es6:9:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/src\package-manager.coffee:14:17)
    at Object.<anonymous> (/src\package-manager.coffee:1:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at NylasEnvConstructor.initialize (/src\nylas-env.es6:171:28)
    at Object.<anonymous> (/src\secondary-window-bootstrap.es6:25:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at setupWindow (file:///C:/Users/user/AppData/Local/nylas/app-2.0.10/resources/app.asar/static/index.js:64:3)
    at window.onload (file:///C:/Users/user/AppData/Local/nylas/app-2.0.10/resources/app.asar/static/index.js:95:5)handleSetupError @ index.js:28
```

Since Nylas Mail isn't released yet for Windows, I'm fairly sure this is in error.

**Comment by Zangoran** [comment]
I have also just recieved this error. Any help would be appreciated!

**Comment by michaelmulligan** [comment]
Likewise, same error. Any workarounds until it's fixed?

**Comment by hallamoore** [comment]
There's not really a work around, but I'm working on a hot fix. Should be out within the hour!

**Comment by hallamoore** [comment]
This should be fixed now, but you may have to delete that `app-2.0.10` folder or reinstall 1.5.0. (There should be an executable at https://github.com/nylas/nylas-mail/releases/tag/1.5.0) 

Let us know if there are any more issues~

**Comment by jstejada** [comment]
The windows build has been fixed. If you've downloaded a bad build, you can re-download it from nylas.com/download

**Comment by ygoyal25** [comment]
Hi,
I tried to install 'npm react-alert' package and as soon as it was installed, nylas stopped working with the message saying 'Cannot find module 'isomorphic-core' at Module._resolveFilename'. Could anyone please help me with this.

**Comment by tayfunyasar** [comment]
same issue here.
