### ISSUE TITLE
Windows build is broken in 2.0.x

### ISSUE THREAD

**Issue by jstejada** [nylas/nylas-mail#3367]
Errors with the following error:
```
index.js:28 Error: Cannot find module 'isomorphic-core'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\user\AppData\Local\nylas\app-2.0.10\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/src\module-cache.coffee:267:20)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/src\flux\stores\database-store.es6:9:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/src\package-manager.coffee:14:17)
    at Object.<anonymous> (/src\package-manager.coffee:1:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at NylasEnvConstructor.initialize (/src\nylas-env.es6:171:28)
    at Object.<anonymous> (/src\secondary-window-bootstrap.es6:25:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at setupWindow (file:///C:/Users/user/AppData/Local/nylas/app-2.0.10/resources/app.asar/static/index.js:64:3)
    at window.onload (file:///C:/Users/user/AppData/Local/nylas/app-2.0.10/resources/app.asar/static/index.js:95:5)handleSetupError @ index.js:28
```

**Comment by jstejada** [comment]
The build has been fixed. If you've downloaded a bad build, you can re-download it from nylas.com/download

**Comment by ArchangeGabriel** [comment]
Dupe of https://github.com/nylas/nylas-mail/issues/3366 btw.

**Comment by pierrebeaucamp** [comment]
Can confirm this working. Thanks for the quick fix.

**Comment by hallamoore** [comment]
(Not quite a dupe of #3366, that one focused more on the fact that people were forced to update from old N1 to the new Nylas Mail while the two are supposed to be separate)
