### ISSUE TITLE
Nylas N1 pro update broke the app

### ISSUE THREAD

**Issue by FruitDZign** [nylas/nylas-mail#3369]
Windows 10
Nylas N1 Pro / No third party plugins
Problem not specific to an email provider
Permanent problem
**Problem description:**
Nylas N1 Pro prompted me to update the app so I accepted (small prompt window at the bottom left). Since then, it is impossible to launch the app : when I click on it, it opens two windows. The first one is empty and the second one displays the Developer Tools with the following error in the console :
```
Error: Cannot find module 'isomorphic-core'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\mohse\AppData\Local\Nylas\app-2.0.10\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/src\module-cache.coffee:267:20)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/src\flux\stores\database-store.es6:9:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/src\package-manager.coffee:14:17)
    at Object.<anonymous> (/src\package-manager.coffee:1:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at NylasEnvConstructor.initialize (/src\nylas-env.es6:171:28)
    at Object.<anonymous> (/src\secondary-window-bootstrap.es6:25:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at setupWindow (file:///C:/Users/mohse/AppData/Local/Nylas/app-2.0.10/resources/app.asar/static/index.js:64:3)
    at window.onload (file:///C:/Users/mohse/AppData/Local/Nylas/app-2.0.10/resources/app.asar/static/index.js:95:5)handleSetupError @ index.js:28
```

**Comment by ArchangeGabriel** [comment]
Apparently, there was an issue with the Windows build. It’s supposed to be fixed now, read at https://github.com/nylas/nylas-mail/issues/3366.
