### ISSUE TITLE
cannot sync mail: IMAP protocol error.

### ISSUE THREAD

**Issue by xxv** [nylas/nylas-mail#3407]
##### Are there any related issues?

could not find any obvious ones

##### What operating system are you using?
Debian GNU/Linux 9 (stretch)

##### What version of Nylas Mail are you using?
2.0.15
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Attempting to connect to Courier IMAP 4.8.0 running on my own server

I was able to login far enough for it to load the folder list, but it hasn't been able to load the contents of any folders yet. Each time it gives me a red warning that says, "Encountered an error syncing [my email address]" with a "Try Again" button.

```
{ Error: Error: Error in IMAP command received by server.
    at NylasError (errors.es6:1:8)
    at IMAPProtocolError (imap-errors.es6:22:5)
    at convertImapError (imap-errors.es6:140:15)
    at wrappedReject (imap-connection.es6:245:34)
    at imap-connection.es6:264:11
    at throw (<anonymous>)
From previous event:
    at imap-connection.es6:234:20
    at next (<anonymous>)
    at step (imap-connection.es6:9:1)
From previous event:
    at imap-connection.es6:9:1
    at imap-box.es6:55:17
    at next (<anonymous>)
    at step (/usr/share/nylas-mail/resources/app.asar/node_modules/isomorphic-core/src/imap-box.es6:3:191)
From previous event:
    at /usr/share/nylas-mail/resources/app.asar/node_modules/isomorphic-core/src/imap-box.es6:3:99
    at /internal_packages/client-sync/src/local-sync-worker/sync-tasks/fetch-messages-in-folder.imap.es6:255:21
    at next (<anonymous>)
    at resume (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/sync-tasks/fetch-messages-in-folder.imap.js:3:448)
    at /usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/sync-tasks/fetch-messages-in-folder.imap.js:3:367
From previous event:
    at AsyncGenerator.send [as _invoke] (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/sync-tasks/fetch-messages-in-folder.imap.js:3:169)
    at advance (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:78:31)
    at err (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:110:17)
From previous event:
    at FetchMessagesInFolderIMAP._runGenerator (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:63:12)
    at advance (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:94:30)
  message: 'Error: Error in IMAP command received by server.',
  userMessage: 'IMAP protocol error. Please contact support@nylas.com.',
  statusCode: 401,
  source: 'protocol',
  __stackCleaned__: true } { fingerprint: 
   [ '{{ default }}',
     'sync loop',
     'Error: Error in IMAP command received by server.' ],
  rateLimit: 
   { ratePerHour: 30,
     key: 'SyncError:SyncLoop:Error: Error in IMAP command received by server.' },
  pluginIds: [ 'client-sync' ] }
```

**Comment by tvk7** [comment]
Got the same error (Ubuntu 16.04). What Mailserser you are using. We use courier. Maybe related...

**Comment by mcg** [comment]
Also using Courier IMAP, similar issues....
```
 Error: Error: Invalid mailbox name.
    at NylasError (errors.es6:1:8)
    at IMAPProtocolError (imap-errors.es6:22:5)
    at convertImapError (imap-errors.es6:147:15)
    at wrappedReject (imap-connection.es6:245:34)
    at imap-connection.es6:264:11
    at throw (<anonymous>)
    at step (imap-connection.es6:9:1)
    at imap-connection.es6:9:1
    at tryCatcher (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
  message: 'Error: Invalid mailbox name.',
  userMessage: 'IMAP protocol error. Try to first remove your account from Nylas Mail, then re-add it and try again.',
  statusCode: 401,
  source: 'protocol' } { pluginIds: [] }
{ Error: Error: Error in IMAP command received by server.
    at NylasError (errors.es6:1:8)
    at IMAPProtocolError (imap-errors.es6:22:5)
    at convertImapError (imap-errors.es6:147:15)
    at wrappedReject (imap-connection.es6:245:34)
    at imap-connection.es6:264:11
    at throw (<anonymous>)
    at step (imap-connection.es6:9:1)
    at imap-connection.es6:9:1
    at tryCatcher (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
  message: 'Error: Error in IMAP command received by server.',
  userMessage: 'IMAP protocol error. Try to first remove your account from Nylas Mail, then re-add it and try again.',
  statusCode: 401,
  source: 'protocol' } { pluginIds: [] }
```

**Comment by treviser** [comment]
Same issue here. Ubuntu 16.04 LTS, trying to connect to my Mail Service Provider. Also the folder list gets loaded, but emails are not synched.

**Comment by ipcross** [comment]
+1 
Got the same error (Archlinux).   
nylas-mail-bin 2.0.32-1

**Comment by tvk7** [comment]
They won't or can do maybe anything to solve. Sorry to say but the mem/cpu footprint/load is anyway ridiculous. But nice gui and interface.

**Comment by smdahmed** [comment]
I havent looked into the error but I have issues retrieving mail.com IMAP after a few days. The emails cant be retrieved any more.
