### ISSUE TITLE
Adding Gmail account "Request aborted by client"

### ISSUE THREAD

**Issue by pjcarvalho** [nylas/nylas-mail#3422]
On adding Gmail account to Nylas Mail (v2.0.1) the following error is shown after good browser authorization: 
"Sorry, we had trouble logging you in
"Request aborted by client"
Please try again. If you continue to see this error contact support@nylas.com"

I'm in a institution which I know that do not allow sending email using google smtp server. I don't know if this is the problem but normally I setup the google account with my institution smtp server. However, nylas mail do not allow me to setup manually the google account locking the "Connect Account" button.

**Comment by esanguin** [comment]
Getting the same error on fedora, here is the beginning of the log :

> Error
>     at new APIError (/src/flux/errors.es6:57:19)
>     at Request.<anonymous> (/src/flux/nylas-api-request.es6:89:30)
>     at emitNone (events.js:86:13)
>     at Request.emit (events.js:185:7)
>     at Request.abort (/usr/share/nylas-mail/resources/app.asar/node_modules/request/request.js:1096:8)
>     at ClientRequest.<anonymous> (/usr/share/nylas-mail/resources/app.asar/node_modules/request/request.js:777:16)
>     at ClientRequest.g (events.js:286:16)
>     at emitNone (events.js:86:13)
>     at ClientRequest.emit (events.js:185:7)
>     at Socket.emitTimeout (_http_client.js:614:10)
>     at Socket.g (events.js:286:16)
>     at emitNone (events.js:86:13)
>     at Socket.emit (events.js:185:7)
>     at Socket._onTimeout (net.js:334:8)
>     at tryOnTimeout (timers.js:232:11)
>     at Timer.listOnTimeout (timers.js:202:5)
>

**Comment by SergeyPirogov** [comment]
The same at Ubuntu 16.04

**Comment by LeGast00n** [comment]
Same symptom on Mac (don't know about the logs)

**Comment by emadow** [comment]
Same on Mac -- and I've tried two gmail accounts (one personal, one g-suite). I've even tried removing the app altogether, along with `Application Support` components, and `~/.nylas_mail` contents.

**Comment by franapoli** [comment]
Same on Nylas 2.0.32, Ubuntu 16.04.

**Comment by floatingrain** [comment]
No one of Nylas care about this? That's rediculars!
