### ISSUE TITLE
Mail stops syncing after a while, restarting/reloading application makes no difference

### ISSUE THREAD

**Issue by roja45** [nylas/nylas-mail#3493]
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10

##### What version of Nylas Mail are you using?
2.0.18
--

**Bug?**
Second time this has happened, the application seems to stop syncing, it's not pulling down new emails, I can't delete.  it shows me a message that it has deleted but nothing changes on screen.
I've restarted the program, no difference, and I tried the reload option, no difference.

The computer was hibernated prior to the issue.

The last time this happened, you pushed out an unrelated update, and the reinstall fixed the issue.

I have these errors in the log:

{"host":"","timestamp":"2017-04-28T13:50:35.635Z","payload":"Error\n    at new APIError (/src\\flux\\errors.es6:57:19)\n    at Request._callback (/src\\flux\\nylas-api-request.es6:75:26)\n    at Request.self.callback (C:\\Users\\*\\AppData\\Local\\NylasMail\\app-2.0.18\\resources\\app.asar\\node_modules\\request\\request.js:186:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (C:\\Users\\*\\AppData\\Local\\NylasMail\\app-2.0.18\\resources\\app.asar\\node_modules\\request\\request.js:1081:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (C:\\Users\\*\\AppData\\Local\\NylasMail\\app-2.0.18\\resources\\app.asar\\node_modules\\request\\request.js:1001:12)\n    at IncomingMessage.g (events.js:286:16)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"}
{"host":"","timestamp":"2017-04-28T13:50:35.635Z","payload":{"rateLimit":{"ratePerHour":30,"key":"UnhandledRejection:Error\n    at new APIError (/src\\flux\\errors.es6:57:19)\n    at Request._callback (/src\\flux\\nylas-api-request.es6:75:26)\n    at Request.self.callback (C:\\Users\\*\\AppData\\Local\\NylasMail\\app-2.0.18\\resources\\app.asar\\node_modules\\request\\request.js:186:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (C:\\Users\\*\\AppData\\Local\\NylasMail\\app-2.0.18\\resources\\app.asar\\node_modules\\request\\request.js:1081:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (C:\\Users\\*\\AppData\\Local\\NylasMail\\app-2.0.18\\resources\\app.asar\\node_modules\\request\\request.js:1001:12)\n    at IncomingMessage.g (events.js:286:16)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"},"pluginIds":[]}}
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by andrewrphillips** [comment]
Similar problem on Mac OS 10.12.4. Asking the client to check for updates seems to make it connect to the internet and some email is received or sent, but not all messages are being downloaded from the server.

**Comment by notatamas** [comment]
This issue is present on Ubuntu 16.04 as well.

**Comment by cristianfb1989** [comment]
Similar problem on Win 10 . The mails aren't synchronized.
