### ISSUE TITLE
Cannot send mail: "Cannot read property 'substring' of undefined"

### ISSUE THREAD

**Issue by Xananax** [nylas/nylas-mail#3583]
##### Are there any related issues?

...

##### What operating system are you using?

Arch Linux

##### What version of Nylas Mail are you using?

1.0.26, built from the git version using the AUR package

--

When sending an email, the sending fails with:

```sh
Cannot read property 'substring' of undefined
```

(full log below)

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't know; I only use gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Happens for every mail, so, eminently reproducible

I would've liked to debug further, but I'm having trouble understanding where this file is and how I can intervene on it.

--

Full log:

```sh
Cannot read property 'substring' of undefinedTypeError: Cannot read property 'substring' of undefined
    at pathForBodyFile (message-body-utils.es6:32:21)
    at Object.writeBody (message-body-utils.es6:41:20)
    at setBody (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/models/message.js:39:52)
    at Instance.set (/usr/share/nylas-mail/resources/app.asar/node_modules/sequelize/lib/instance.js:312:32)
    at obj.(anonymous function) [as set] (/internal_packages/client-sync/src/shared/shim-sequelize.es6:19:27)
    at Instance.set (/usr/share/nylas-mail/resources/app.asar/node_modules/sequelize/lib/instance.js:294:16)
    at obj.(anonymous function) [as set] (/internal_packages/client-sync/src/shared/shim-sequelize.es6:19:27)
    at initValues (/usr/share/nylas-mail/resources/app.asar/node_modules/sequelize/lib/instance.js:63:8)
    at Instance (/usr/share/nylas-mail/resources/app.asar/node_modules/sequelize/lib/instance.js:107:14)
    at new Instance (/usr/share/nylas-mail/resources/app.asar/node_modules/sequelize/lib/model.js:686:14)
    at Model.build (/usr/share/nylas-mail/resources/app.asar/node_modules/sequelize/lib/model.js:1764:10)
    at Object.<anonymous> (message-utils.es6:430:28)
    at next (<anonymous>)
    at step (message-utils.es6:2:1)
    at Object.<anonymous> (message-utils.es6:2:1)
    at /internal_packages/client-sync/src/local-sync-worker/syncback-tasks/send-message.smtp.es6:21:40
    at next (<anonymous>)
    at resume (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/syncback-tasks/send-message.smtp.js:3:448)
    at /usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/syncback-tasks/send-message.smtp.js:3:367
From previous event:
    at AsyncGenerator.send [as _invoke] (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/syncback-tasks/send-message.smtp.js:3:169)
    at advance (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:78:31)
    at err (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:110:17)
From previous event:
    at Interruptible._runGenerator (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:63:12)
    at err (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:133:32)
From previous event:
    at Interruptible.run (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:127:28)
    at /internal_packages/client-sync/src/local-sync-worker/syncback-tasks/syncback-task.es6:56:48
    at next (<anonymous>)
    at step (/internal_packages/client-sync/src/local-sync-worker/syncback-tasks/syncback-task.es6:2:1)
From previous event:
    at /internal_packages/client-sync/src/local-sync-worker/syncback-tasks/syncback-task.es6:2:1
    at /internal_packages/client-sync/src/local-sync-worker/syncback-task-runner.es6:174:37
    at next (<anonymous>)
    at step (/internal_packages/client-sync/src/local-sync-worker/syncback-task-runner.es6:4:1)
From previous event:
    at /internal_packages/client-sync/src/local-sync-worker/syncback-task-runner.es6:4:1
    at /internal_packages/client-sync/src/local-sync-worker/sync-worker.es6:546:32
    at next (<anonymous>)
    at resume (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/sync-worker.js:3:448)
    at /usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/sync-worker.js:3:367
From previous event:
    at AsyncGenerator.send [as _invoke] (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/local-sync-worker/sync-worker.js:3:169)
    at advance (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:78:31)
    at err (/usr/share/nylas-mail/resources/app.asar/internal_packages/client-sync/src/shared/interruptible.js:110:17)APIError: Cannot read property 'substring' of undefined
    at new APIError (/src/flux/errors.es6:57:19)
    at _actions2.default.didReceiveSyncbackRequestDeltas.listen.syncbackRequests (/src/flux/syncback-task-api-request.es6:30:25)
    at EventEmitter.eventHandler (/usr/share/nylas-mail/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/nylas-mail/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/nylas-mail/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Function.functor [as didReceiveSyncbackRequestDeltas] (/usr/share/nylas-mail/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at DeltaProcessor._notifyOfSyncbackRequestDeltas (/src/services/delta-processor.es6:139:13)
    at /src/services/delta-processor.es6:77:12
    at next (<anonymous>)
    at step (/usr/share/nylas-mail/resources/app.asar/src/services/delta-processor.js:35:191)
    at /usr/share/nylas-mail/resources/app.asar/src/services/delta-processor.js:35:361
From previous event:
    at Function.listenForRequest (/src/flux/syncback-task-api-request.es6:22:12)
    at /src/flux/syncback-task-api-request.es6:76:32
    at next (<anonymous>)
    at step (/src/flux/syncback-task-api-request.es6:6:1)
From previous event:
    at /src/flux/syncback-task-api-request.es6:6:1
From previous event:
    at SyncbackTaskAPIRequest.run (/src/flux/syncback-task-api-request.es6:70:12)
    at SendDraftTask.<anonymous> (/src/flux/tasks/send-draft-task.es6:127:33)
    at next (<anonymous>)
    at step (/src/flux/tasks/send-draft-task.es6:15:1)
From previous event:
    at SendDraftTask._sendWithSingleBody (/src/flux/tasks/send-draft-task.es6:15:1)
    at /src/flux/tasks/send-draft-task.es6:96:18
    at next (<anonymous>)
    at step (/src/flux/tasks/send-draft-task.es6:15:1)
From previous event:
    at /src/flux/tasks/send-draft-task.es6:15:1
From previous event:
    at SendDraftTask.performRemote (/src/flux/tasks/send-draft-task.es6:46:6)
    at SendDraftTask.runRemote (/src/flux/tasks/task.es6:230:19)
    at TaskQueue._processTask (/src/flux/stores/task-queue.coffee:258:10)
    at TaskQueue._processTask (/src/flux/stores/task-queue.coffee:1:1)
    at TaskQueue._processQueue (/src/flux/stores/task-queue.coffee:222:8)
    at TaskQueue._processQueue (/src/flux/stores/task-queue.coffee:1:1)
    at /src/flux/stores/task-queue.coffee:372:10
    at /usr/share/nylas-mail/resources/app.asar/node_modules/underscore/underscore.js:768:19
```

**Comment by adenix** [comment]
I am having a similar issue. I receive a pop up telling me that my message could not be added to the sent folder because it `Cannot read property 'substring' of undefined`, however, my email is sent.

**Comment by adenix** [comment]
This issue makes Nylas Mail 100% unusable as it has progress to no longer receiving emails. Can someone please start working on this?

**Comment by brianmcgee** [comment]
I'm experiencing the same error as @Xananax with a similar setup (running Manjaro). Like @adenix said this makes Nylas Mail pretty much unusable.

**Comment by agrudzinsky** [comment]
After reading nice reviews about nylas mail client, I have installed 

> aur/nylas-mail-git 1:1.0.26.1389.g6d2c2b2af-1

 on my Arch Linux system.  I am getting the same error.  Can't use it.  This is a critical error.
