### ISSUE TITLE
nylas-mail can't start in ubuntu 17.04

### ISSUE THREAD

**Issue by achillis2** [nylas/nylas-mail#3597]
![nylas crash](https://user-images.githubusercontent.com/11142556/27513012-e21dd716-591b-11e7-8aa9-c81d5acb8744.png)

##### Are there any related issues?

...

##### What operating system are you using? Ubuntu 17.04
...

##### What version of Nylas Mail are you using? 2.0.32
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? Gmail
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...
{"host":"mubuntu","timestamp":"2017-06-25T01:26:42.450Z","payload":"App load time: 399ms\n"}
{"host":"mubuntu","timestamp":"2017-06-25T01:26:51.717Z","payload":"Error: ENOENT: no such file or directory, open '/home/ding/.nylas-mail/compile-cache/less/aee3e13f2ca5a3480db9b5ade291e84fdbf5c6b1/imports.json'\n    at Error (native)\n    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)\n    at Object.fs.writeFileSync (fs.js:1343:33)\n    at Object.writeFileSync (/usr/share/nylas-mail/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:288:17)\n    at LessCache.module.exports.LessCache.writeJson (/usr/share/nylas-mail/resources/app.asar/node_modules/less-cache/lib/less-cache.js:152:17)\n    at LessCache.module.exports.LessCache.setImportPaths (/usr/share/nylas-mail/resources/app.asar/node_modules/less-cache/lib/less-cache.js:113:12)\n    at new LessCache (/usr/share/nylas-mail/resources/app.asar/node_modules/less-cache/lib/less-cache.js:32:12)\n    at new LessCompileCache (/src/less-compile-cache.es6:20:18)\n    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/src/theme-manager.coffee:200:24)\n    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/src/theme-manager.coffee:193:8)\n    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/src/theme-manager.coffee:168:18)\n    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/src/theme-manager.coffee:177:6)\n    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/src/theme-manager.coffee:174:6)\n    at _storeRegistry2.default.activateAllStores.then (/src/nylas-env.es6:856:19)\n    at tryCatcher (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:691:18)\n    at Async._drainQueue (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)\n    at Async.drainQueues (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)"}
{"host":"mubuntu","timestamp":"2017-06-25T01:26:51.718Z","payload":{"rateLimit":{"ratePerHour":30,"key":"UnhandledRejection:Error: ENOENT: no such file or directory, open '/home/ding/.nylas-mail/compile-cache/less/aee3e13f2ca5a3480db9b5ade291e84fdbf5c6b1/imports.json'\n    at Error (native)\n    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)\n    at Object.fs.writeFileSync (fs.js:1343:33)\n    at Object.writeFileSync (/usr/share/nylas-mail/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:288:17)\n    at LessCache.module.exports.LessCache.writeJson (/usr/share/nylas-mail/resources/app.asar/node_modules/less-cache/lib/less-cache.js:152:17)\n    at LessCache.module.exports.LessCache.setImportPaths (/usr/share/nylas-mail/resources/app.asar/node_modules/less-cache/lib/less-cache.js:113:12)\n    at new LessCache (/usr/share/nylas-mail/resources/app.asar/node_modules/less-cache/lib/less-cache.js:32:12)\n    at new LessCompileCache (/src/less-compile-cache.es6:20:18)\n    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/src/theme-manager.coffee:200:24)\n    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/src/theme-manager.coffee:193:8)\n    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/src/theme-manager.coffee:168:18)\n    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/src/theme-manager.coffee:177:6)\n    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/src/theme-manager.coffee:174:6)\n    at _storeRegistry2.default.activateAllStores.then (/src/nylas-env.es6:856:19)\n    at tryCatcher (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:691:18)\n    at Async._drainQueue (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)\n    at Async.drainQueues (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)"},"pluginIds":[]}}
{"host":"mubuntu","timestamp":"2017-06-25T01:26:51.774Z","payload":"{ Error: ENOENT: no such file or directory, open '/home/ding/.nylas-mail/compile-cache/less/aee3e13f2ca5a3480db9b5ade291e84fdbf5c6b1/imports.json'\n    at Error (native)\n    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)\n    at Object.fs.writeFileSync (fs.js:1343:33)\n    at Object.writeFileSync (/usr/share/nylas-mail/resources/app.asar/node_modules/fs-plus/lib/fs-plus.js:288:17)\n    at LessCache.module.exports.LessCache.writeJson (/usr/share/nylas-mail/resources/app.asar/node_modules/less-cache/lib/less-cache.js:152:17)\n    at LessCache.module.exports.LessCache.setImportPaths (/usr/share/nylas-mail/resources/app.asar/node_modules/less-cache/lib/less-cache.js:113:12)\n    at new LessCache (/usr/share/nylas-mail/resources/app.asar/node_modules/less-cache/lib/less-cache.js:32:12)\n    at new LessCompileCache (/src/less-compile-cache.es6:20:18)\n    at ThemeManager.module.exports.ThemeManager.loadLessStylesheet (/src/theme-manager.coffee:200:24)\n    at ThemeManager.module.exports.ThemeManager.loadStylesheet (/src/theme-manager.coffee:193:8)\n    at ThemeManager.module.exports.ThemeManager.requireStylesheet (/src/theme-manager.coffee:168:18)\n    at ThemeManager.module.exports.ThemeManager.reloadBaseStylesheets (/src/theme-manager.coffee:177:6)\n    at ThemeManager.module.exports.ThemeManager.loadBaseStylesheets (/src/theme-manager.coffee:174:6)\n    at _storeRegistry2.default.activateAllStores.then (/src/nylas-env.es6:856:19)\n    at tryCatcher (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromise0 (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:612:10)\n    at Promise._settlePromises (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/promise.js:691:18)\n    at Async._drainQueue (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)\n    at Async.drainQueues (/usr/share/nylas-mail/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)\n  message: 'ENOENT: no such file or directory, open \\'/home/ding/.nylas-mail/compile-cache/less/aee3e13f2ca5a3480db9b5ade291e84fdbf5c6b1/imports.json\\'',\n  errno: -2,\n  code: 'ENOENT',\n  syscall: 'open',\n  path: '/home/ding/.nylas-mail/compile-cache/less/aee3e13f2ca5a3480db9b5ade291e84fdbf5c6b1/imports.json' } { pluginIds: [] }\n"}
{"host":"mubuntu","timestamp":"2017-06-25T01:26:51.972Z","payload":"Invalid api key\n"}
{"host":"mubuntu","timestamp":"2017-06-25T01:26:51.972Z","payload":"401\n"}
{"host":"mubuntu","timestamp":"2017-06-25T01:26:52.040Z","payload":"IncomingMessage {\n  _readableState: \n   ReadableState {\n     objectMode: false,\n     highWaterMark: 16384,\n     buffer: BufferList { head: null, tail: null, length: 0 },\n     length: 0,\n     pipes: null,\n     pipesCount: 0,\n     flowing: null,\n     ended: false,\n     endEmitted: false,\n     reading: false,\n     sync: true,\n     needReadable: false,\n     emittedReadable: false,\n     readableListening: false,\n     resumeScheduled: false,\n     defaultEncoding: 'utf8',\n     ranOut: false,\n     awaitDrain: 0,\n     readingMore: true,\n     decoder: \n      StringDecoder {\n        encoding: 'utf8',\n        fillLast: [Function: utf8FillLast],\n        lastNeed: 0,\n        lastTotal: 0,\n        lastChar: <Buffer 00 00 00 00> },\n     encoding: 'utf8' },\n  readable: true,\n  domain: null,\n  _events: { end: [Function: responseOnEnd] },\n  _eventsCount: 1,\n  _maxListeners: undefined,\n  socket: \n   TLSSocket {\n     _tlsOptions: \n      { pipe: null,\n        secureContext: [Object],\n        isServer: false,\n        requestCert: true,\n        rejectUnauthorized: true,\n        session: undefined,\n        NPNProtocols: undefined,\n        ALPNProtocols: undefined,\n        requestOCSP: undefined },\n     _secureEstablished: true,\n     _securePending: false,\n     _newSessionPending: false,\n     _controlReleased: true,\n     _SNICallback: null,\n     servername: null,\n     npnProtocol: false,\n     alpnProtocol: false,\n     authorized: true,\n     authorizationError: null,\n     encrypted: true,\n     _events: \n      { close: [Object],\n        end: [Object],\n        finish: [Function: onSocketFinish],\n        _socketEnd: [Function: onSocketEnd],\n        secure: [Function],\n        free: [Function: onFree],\n        agentRemove: [Function: onRemove],\n        drain: [Function: ondrain],\n        error: [Function: socketErrorListener],\n        data: [Function: socketOnData] },\n     _eventsCount: 10,\n     connecting: false,\n     _hadError: false,\n     _handle: \n      TLSWrap {\n        bytesRead: 564,\n        _externalStream: {},\n        fd: 94,\n        _parent: [Object],\n        _parentWrap: undefined,\n        _secureContext: [Object],\n        reading: true,\n        owner: [Circular],\n        onread: [Function: onread],\n        writeQueueSize: 1,\n        onhandshakestart: [Function],\n        onhandshakedone: [Function],\n        onocspresponse: [Function],\n        onerror: [Function] },\n     _parent: null,\n     _host: 'sentry.io',\n     _readableState: \n      ReadableState {\n        objectMode: false,\n        highWaterMark: 16384,\n        buffer: [Object],\n        length: 0,\n        pipes: null,\n        pipesCount: 0,\n        flowing: true,\n        ended: false,\n        endEmitted: false,\n        reading: false,\n        sync: false,\n        needReadable: true,\n        emittedReadable: false,\n        readableListening: false,\n        resumeScheduled: false,\n        defaultEncoding: 'utf8',\n        ranOut: false,\n        awaitDrain: 0,\n        readingMore: false,\n        decoder: null,\n        encoding: null },\n     readable: true,\n     domain: null,\n     _maxListeners: undefined,\n     _writableState: \n      WritableState {\n        objectMode: false,\n        highWaterMark: 16384,\n        needDrain: false,\n        ending: false,\n        ended: false,\n        finished: false,\n        decodeStrings: false,\n        defaultEncoding: 'utf8',\n        length: 0,\n        writing: false,\n        corked: 0,\n        sync: false,\n        bufferProcessing: false,\n        onwrite: [Function],\n        writecb: null,\n        writelen: 0,\n        bufferedRequest: null,\n        lastBufferedRequest: null,\n        pendingcb: 0,\n        prefinished: false,\n        errorEmitted: false,\n        bufferedRequestCount: 0,\n        corkedRequestsFree: [Object] },\n     writable: true,\n     allowHalfOpen: false,\n     destroyed: false,\n     _bytesDispatched: 4979,\n     _sockname: null,\n     _pendingData: null,\n     _pendingEncoding: '',\n     server: undefined,\n     _server: null,\n     ssl: \n      TLSWrap {\n        bytesRead: 564,\n        _externalStream: {},\n        fd: 94,\n        _parent: [Object],\n        _parentWrap: undefined,\n        _secureContext: [Object],\n        reading: true,\n        owner: [Circular],\n        onread: [Function: onread],\n        writeQueueSize: 1,\n        onhandshakestart: [Function],\n        onhandshakedone: [Function],\n        onocspresponse: [Function],\n        onerror: [Function] },\n     _requestCert: true,\n     _rejectUnauthorized: true,\n     parser: \n      HTTPParser {\n        '0': [Function: parserOnHeaders],\n        '1': [Function: parserOnHeadersComplete],\n        '2': [Function: parserOnBody],\n        '3': [Function: parserOnMessageComplete],\n        '4': null,\n        _headers: [],\n        _url: '',\n        _consumed: false,\n        socket: [Circular],\n        incoming: [Circular],\n        outgoing: [Object],\n        maxHeaderPairs: 2000,\n        onIncoming: [Function: parserOnIncomingClient] },\n     _httpMessage: \n      ClientRequest {\n        domain: null,\n        _events: [Object],\n        _eventsCount: 2,\n        _maxListeners: undefined,\n        output: [],\n        outputEncodings: [],\n        outputCallbacks: [],\n        outputSize: 0,\n        writable: true,\n        _last: true,\n        chunkedEncoding: false,\n        shouldKeepAlive: false,\n        useChunkedEncodingByDefault: true,\n        sendDate: false,\n        _removedHeader: [Object],\n        _contentLength: 4648,\n        _hasBody: true,\n        _trailer: '',\n        finished: true,\n        _headerSent: true,\n        socket: [Circular],\n        connection: [Circular],\n        _header: 'POST /api/144447/store/ HTTP/1.1\\r\\nX-Sentry-Auth: Sentry sentry_version=5, sentry_timestamp=1498354011802, sentry_client=raven-node/1.1.4, sentry_key=a556c0165bc74435952c95dccc5938ec, sentry_secret=484978beb99f40208cb86610e66bead6\\r\\nContent-Type: application/octet-stream\\r\\nContent-Length: 4648\\r\\nHost: sentry.io\\r\\nConnection: close\\r\\n\\r\\n',\n        _headers: [Object],\n        _headerNames: [Object],\n        _onPendingData: null,\n        agent: [Object],\n        socketPath: undefined,\n        method: 'POST',\n        path: '/api/144447/store/',\n        _ended: false,\n        parser: [Object],\n        res: [Circular] },\n     read: [Function],\n     _consuming: true },\n  connection: \n   TLSSocket {\n     _tlsOptions: \n      { pipe: null,\n        secureContext: [Object],\n        isServer: false,\n        requestCert: true,\n        rejectUnauthorized: true,\n        session: undefined,\n        NPNProtocols: undefined,\n        ALPNProtocols: undefined,\n        requestOCSP: undefined },\n     _secureEstablished: true,\n     _securePending: false,\n     _newSessionPending: false,\n     _controlReleased: true,\n     _SNICallback: null,\n     servername: null,\n     npnProtocol: false,\n     alpnProtocol: false,\n     authorized: true,\n     authorizationError: null,\n     encrypted: true,\n     _events: \n      { close: [Object],\n        end: [Object],\n        finish: [Function: onSocketFinish],\n        _socketEnd: [Function: onSocketEnd],\n        secure: [Function],\n        free: [Function: onFree],\n        agentRemove: [Function: onRemove],\n        drain: [Function: ondrain],\n        error: [Function: socketErrorListener],\n        data: [Function: socketOnData] },\n     _eventsCount: 10,\n     connecting: false,\n     _hadError: false,\n     _handle: \n      TLSWrap {\n        bytesRead: 564,\n        _externalStream: {},\n        fd: 94,\n        _parent: [Object],\n        _parentWrap: undefined,\n        _secureContext: [Object],\n        reading: true,\n        owner: [Circular],\n        onread: [Function: onread],\n        writeQueueSize: 1,\n        onhandshakestart: [Function],\n        onhandshakedone: [Function],\n        onocspresponse: [Function],\n        onerror: [Function] },\n     _parent: null,\n     _host: 'sentry.io',\n     _readableState: \n      ReadableState {\n        objectMode: false,\n        highWaterMark: 16384,\n        buffer: [Object],\n        length: 0,\n        pipes: null,\n        pipesCount: 0,\n        flowing: true,\n        ended: false,\n        endEmitted: false,\n        reading: false,\n        sync: false,\n        needReadable: true,\n        emittedReadable: false,\n        readableListening: false,\n        resumeScheduled: false,\n        defaultEncoding: 'utf8',\n        ranOut: false,\n        awaitDrain: 0,\n        readingMore: false,\n        decoder: null,\n        encoding: null },\n     readable: true,\n     domain: null,\n     _maxListeners: undefined,\n     _writableState: \n      WritableState {\n        objectMode: false,\n        highWaterMark: 16384,\n        needDrain: false,\n        ending: false,\n        ended: false,\n        finished: false,\n        decodeStrings: false,\n        defaultEncoding: 'utf8',\n        length: 0,\n        writing: false,\n        corked: 0,\n        sync: false,\n        bufferProcessing: false,\n        onwrite: [Function],\n        writecb: null,\n        writelen: 0,\n        bufferedRequest: null,\n        lastBufferedRequest: null,\n        pendingcb: 0,\n        prefinished: false,\n        errorEmitted: false,\n        bufferedRequestCount: 0,\n        corkedRequestsFree: [Object] },\n     writable: true,\n     allowHalfOpen: false,\n     destroyed: false,\n     _bytesDispatched: 4979,\n     _sockname: null,\n     _pendingData: null,\n     _pendingEncoding: '',\n     server: undefined,\n     _server: null,\n     ssl: \n      TLSWrap {\n        bytesRead: 564,\n        _externalStream: {},\n        fd: 94,\n        _parent: [Object],\n        _parentWrap: undefined,\n        _secureContext: [Object],\n        reading: true,\n        owner: [Circular],\n        onread: [Function: onread],\n        writeQueueSize: 1,\n        onhandshakestart: [Function],\n        onhandshakedone: [Function],\n        onocspresponse: [Function],\n        onerror: [Function] },\n     _requestCert: true,\n     _rejectUnauthorized: true,\n     parser: \n      HTTPParser {\n        '0': [Function: parserOnHeaders],\n        '1': [Function: parserOnHeadersComplete],\n        '2': [Function: parserOnBody],\n        '3': [Function: parserOnMessageComplete],\n        '4': null,\n        _headers: [],\n        _url: '',\n        _consumed: false,\n        socket: [Circular],\n        incoming: [Circular],\n        outgoing: [Object],\n        maxHeaderPairs: 2000,\n        onIncoming: [Function: parserOnIncomingClient] },\n     _httpMessage: \n      ClientRequest {\n        domain: null,\n        _events: [Object],\n        _eventsCount: 2,\n        _maxListeners: undefined,\n        output: [],\n        outputEncodings: [],\n        outputCallbacks: [],\n        outputSize: 0,\n        writable: true,\n        _last: true,\n        chunkedEncoding: false,\n        shouldKeepAlive: false,\n        useChunkedEncodingByDefault: true,\n        sendDate: false,\n        _removedHeader: [Object],\n        _contentLength: 4648,\n        _hasBody: true,\n        _trailer: '',\n        finished: true,\n        _headerSent: true,\n        socket: [Circular],\n        connection: [Circular],\n        _header: 'POST /api/144447/store/ HTTP/1.1\\r\\nX-Sentry-Auth: Sentry sentry_version=5, sentry_timestamp=1498354011802, sentry_client=raven-node/1.1.4, sentry_key=a556c0165bc74435952c95dccc5938ec, sentry_secret=484978beb99f40208cb86610e66bead6\\r\\nContent-Type: application/octet-stream\\r\\nContent-Length: 4648\\r\\nHost: sentry.io\\r\\nConnection: close\\r\\n\\r\\n',\n        _headers: [Object],\n        _headerNames: [Object],\n        _onPendingData: null,\n        agent: [Object],\n        socketPath: undefined,\n        method: 'POST',\n        path: '/api/144447/store/',\n        _ended: false,\n        parser: [Object],\n        res: [Circular] },\n     read: [Function],\n     _consuming: true },\n  httpVersionMajor: 1,\n  httpVersionMinor: 1,\n  httpVersion: '1.1',\n  complete: false,\n  headers: \n   { server: 'nginx',\n     date: 'Sun, 25 Jun 2017 01:26:51 GMT',\n     'content-type': 'application/json',\n     'content-length': '27',\n     connection: 'close',\n     expires: 'Sun, 25 Jun 2017 01:26:51 GMT',\n     'x-content-type-options': 'nosniff',\n     'content-language': 'en',\n     'x-sentry-error': 'Invalid api key',\n     vary: 'Accept-Language, Cookie',\n     'last-modified': 'Sun, 25 Jun 2017 01:26:51 GMT',\n     'x-xss-protection': '1; mode=block',\n     'cache-control': 'max-age=0',\n     'x-frame-options': 'deny',\n     'x-served-by': 'app-59a746',\n     'strict-transport-security': 'max-age=31536000; includeSubDomains; preload' },\n  rawHeaders: \n   [ 'Server',\n     'nginx',\n     'Date',\n     'Sun, 25 Jun 2017 01:26:51 GMT',\n     'Content-Type',\n     'application/json',\n     'Content-Length',\n     '27',\n     'Connection',\n     'close',\n     'Expires',\n     'Sun, 25 Jun 2017 01:26:51 GMT',\n     'X-Content-Type-Options',\n     'nosniff',\n     'Content-Language',\n     'en',\n     'X-Sentry-Error',\n     'Invalid api key',\n     'Vary',\n     'Accept-Language, Cookie',\n     'Last-Modified',\n     'Sun, 25 Jun 2017 01:26:51 GMT',\n     'X-XSS-Protection',\n     '1; mode=block',\n     'Cache-Control',\n     'max-age=0',\n     'X-Frame-Options',\n     'deny',\n     'X-Served-By',\n     'app-59a746',\n     'Strict-Transport-Security',\n     'max-age=31536000; includeSubDomains; preload' ],\n  trailers: {},\n  rawTrailers: [],\n  upgrade: false,\n  url: '',\n  method: null,\n  statusCode: 401,\n  statusMessage: 'UNAUTHORIZED',\n  client: \n   TLSSocket {\n     _tlsOptions: \n      { pipe: null,\n        secureContext: [Object],\n        isServer: false,\n        requestCert: true,\n        rejectUnauthorized: true,\n        session: undefined,\n        NPNProtocols: undefined,\n        ALPNProtocols: undefined,\n        requestOCSP: undefined },\n     _secureEstablished: true,\n     _securePending: false,\n     _newSessionPending: false,\n     _controlReleased: true,\n     _SNICallback: null,\n     servername: null,\n     npnProtocol: false,\n     alpnProtocol: false,\n     authorized: true,\n     authorizationError: null,\n     encrypted: true,\n     _events: \n      { close: [Object],\n        end: [Object],\n        finish: [Function: onSocketFinish],\n        _socketEnd: [Function: onSocketEnd],\n        secure: [Function],\n        free: [Function: onFree],\n        agentRemove: [Function: onRemove],\n        drain: [Function: ondrain],\n        error: [Function: socketErrorListener],\n        data: [Function: socketOnData] },\n     _eventsCount: 10,\n     connecting: false,\n     _hadError: false,\n     _handle: \n      TLSWrap {\n        bytesRead: 564,\n        _externalStream: {},\n        fd: 94,\n        _parent: [Object],\n        _parentWrap: undefined,\n        _secureContext: [Object],\n        reading: true,\n        owner: [Circular],\n        onread: [Function: onread],\n        writeQueueSize: 1,\n        onhandshakestart: [Function],\n        onhandshakedone: [Function],\n        onocspresponse: [Function],\n        onerror: [Function] },\n     _parent: null,\n     _host: 'sentry.io',\n     _readableState: \n      ReadableState {\n        objectMode: false,\n        highWaterMark: 16384,\n        buffer: [Object],\n        length: 0,\n        pipes: null,\n        pipesCount: 0,\n        flowing: true,\n        ended: false,\n        endEmitted: false,\n        reading: false,\n        sync: false,\n        needReadable: true,\n        emittedReadable: false,\n        readableListening: false,\n        resumeScheduled: false,\n        defaultEncoding: 'utf8',\n        ranOut: false,\n        awaitDrain: 0,\n        readingMore: false,\n        decoder: null,\n        encoding: null },\n     readable: true,\n     domain: null,\n     _maxListeners: undefined,\n     _writableState: \n      WritableState {\n        objectMode: false,\n        highWaterMark: 16384,\n        needDrain: false,\n        ending: false,\n        ended: false,\n        finished: false,\n        decodeStrings: false,\n        defaultEncoding: 'utf8',\n        length: 0,\n        writing: false,\n        corked: 0,\n        sync: false,\n        bufferProcessing: false,\n        onwrite: [Function],\n        writecb: null,\n        writelen: 0,\n        bufferedRequest: null,\n        lastBufferedRequest: null,\n        pendingcb: 0,\n        prefinished: false,\n        errorEmitted: false,\n        bufferedRequestCount: 0,\n        corkedRequestsFree: [Object] },\n     writable: true,\n     allowHalfOpen: false,\n     destroyed: false,\n     _bytesDispatched: 4979,\n     _sockname: null,\n     _pendingData: null,\n     _pendingEncoding: '',\n     server: undefined,\n     _server: null,\n     ssl: \n      TLSWrap {\n        bytesRead: 564,\n        _externalStream: {},\n        fd: 94,\n        _parent: [Object],\n        _parentWrap: undefined,\n        _secureContext: [Object],\n        reading: true,\n        owner: [Circular],\n        onread: [Function: onread],\n        writeQueueSize: 1,\n        onhandshakestart: [Function],\n        onhandshakedone: [Function],\n        onocspresponse: [Function],\n        onerror: [Function] },\n     _requestCert: true,\n     _rejectUnauthorized: true,\n     parser: \n      HTTPParser {\n        '0': [Function: parserOnHeaders],\n        '1': [Function: parserOnHeadersComplete],\n        '2': [Function: parserOnBody],\n        '3': [Function: parserOnMessageComplete],\n        '4': null,\n        _headers: [],\n        _url: '',\n        _consumed: false,\n        socket: [Circular],\n        incoming: [Circular],\n        outgoing: [Object],\n        maxHeaderPairs: 2000,\n        onIncoming: [Function: parserOnIncomingClient] },\n     _httpMessage: \n      ClientRequest {\n        domain: null,\n        _events: [Object],\n        _eventsCount: 2,\n        _maxListeners: undefined,\n        output: [],\n        outputEncodings: [],\n        outputCallbacks: [],\n        outputSize: 0,\n        writable: true,\n        _last: true,\n        chunkedEncoding: false,\n        shouldKeepAlive: false,\n        useChunkedEncodingByDefault: true,\n        sendDate: false,\n        _removedHeader: [Object],\n        _contentLength: 4648,\n        _hasBody: true,\n        _trailer: '',\n        finished: true,\n        _headerSent: true,\n        socket: [Circular],\n        connection: [Circular],\n        _header: 'POST /api/144447/store/ HTTP/1.1\\r\\nX-Sentry-Auth: Sentry sentry_version=5, sentry_timestamp=1498354011802, sentry_client=raven-node/1.1.4, sentry_key=a556c0165bc74435952c95dccc5938ec, sentry_secret=484978beb99f40208cb86610e66bead6\\r\\nContent-Type: application/octet-stream\\r\\nContent-Length: 4648\\r\\nHost: sentry.io\\r\\nConnection: close\\r\\n\\r\\n',\n        _headers: [Object],\n        _headerNames: [Object],\n        _onPendingData: null,\n        agent: [Object],\n        socketPath: undefined,\n        method: 'POST',\n        path: '/api/144447/store/',\n        _ended: false,\n        parser: [Object],\n        res: [Circular] },\n     read: [Function],\n     _consuming: true },\n  _consuming: false,\n  _dumped: false,\n  req: \n   ClientRequest {\n     domain: null,\n     _events: { error: [Function], prefinish: [Function: requestOnPrefinish] },\n     _eventsCount: 2,\n     _maxListeners: undefined,\n     output: [],\n     outputEncodings: [],\n     outputCallbacks: [],\n     outputSize: 0,\n     writable: true,\n     _last: true,\n     chunkedEncoding: false,\n     shouldKeepAlive: false,\n     useChunkedEncodingByDefault: true,\n     sendDate: false,\n     _removedHeader: { 'content-length': false },\n     _contentLength: 4648,\n     _hasBody: true,\n     _trailer: '',\n     finished: true,\n     _headerSent: true,\n     socket: \n      TLSSocket {\n        _tlsOptions: [Object],\n        _secureEstablished: true,\n        _securePending: false,\n        _newSessionPending: false,\n        _controlReleased: true,\n        _SNICallback: null,\n        servername: null,\n        npnProtocol: false,\n        alpnProtocol: false,\n        authorized: true,\n        authorizationError: null,\n        encrypted: true,\n        _events: [Object],\n        _eventsCount: 10,\n        connecting: false,\n        _hadError: false,\n        _handle: [Object],\n        _parent: null,\n        _host: 'sentry.io',\n        _readableState: [Object],\n        readable: true,\n        domain: null,\n        _maxListeners: undefined,\n        _writableState: [Object],\n        writable: true,\n        allowHalfOpen: false,\n        destroyed: false,\n        _bytesDispatched: 4979,\n        _sockname: null,\n        _pendingData: null,\n        _pendingEncoding: '',\n        server: undefined,\n        _server: null,\n        ssl: [Object],\n        _requestCert: true,\n        _rejectUnauthorized: true,\n        parser: [Object],\n        _httpMessage: [Circular],\n        read: [Function],\n        _consuming: true },\n     connection: \n      TLSSocket {\n        _tlsOptions: [Object],\n        _secureEstablished: true,\n        _securePending: false,\n        _newSessionPending: false,\n        _controlReleased: true,\n        _SNICallback: null,\n        servername: null,\n        npnProtocol: false,\n        alpnProtocol: false,\n        authorized: true,\n        authorizationError: null,\n        encrypted: true,\n        _events: [Object],\n        _eventsCount: 10,\n        connecting: false,\n        _hadError: false,\n        _handle: [Object],\n        _parent: null,\n        _host: 'sentry.io',\n        _readableState: [Object],\n        readable: true,\n        domain: null,\n        _maxListeners: undefined,\n        _writableState: [Object],\n        writable: true,\n        allowHalfOpen: false,\n        destroyed: false,\n        _bytesDispatched: 4979,\n        _sockname: null,\n        _pendingData: null,\n        _pendingEncoding: '',\n        server: undefined,\n        _server: null,\n        ssl: [Object],\n        _requestCert: true,\n        _rejectUnauthorized: true,\n        parser: [Object],\n        _httpMessage: [Circular],\n        read: [Function],\n        _consuming: true },\n     _header: 'POST /api/144447/store/ HTTP/1.1\\r\\nX-Sentry-Auth: Sentry sentry_version=5, sentry_timestamp=1498354011802, sentry_client=raven-node/1.1.4, sentry_key=a556c0165bc74435952c95dccc5938ec, sentry_secret=484978beb99f40208cb86610e66bead6\\r\\nContent-Type: application/octet-stream\\r\\nContent-Length: 4648\\r\\nHost: sentry.io\\r\\nConnection: close\\r\\n\\r\\n',\n     _headers: \n      { 'x-sentry-auth': 'Sentry sentry_version=5, sentry_timestamp=1498354011802, sentry_client=raven-node/1.1.4, sentry_key=a556c0165bc74435952c95dccc5938ec, sentry_secret=484978beb99f40208cb86610e66bead6',\n        'content-type': 'application/octet-stream',\n        'content-length': 4648,\n        host: 'sentry.io' },\n     _headerNames: \n      { 'x-sentry-auth': 'X-Sentry-Auth',\n        'content-type': 'Content-Type',\n        'content-length': 'Content-Length',\n        host: 'Host' },\n     _onPendingData: null,\n     agent: \n      Agent {\n        domain: null,\n        _events: [Object],\n        _eventsCount: 1,\n        _maxListeners: undefined,\n        defaultPort: 443,\n        protocol: 'https:',\n        options: [Object],\n        requests: {},\n        sockets: [Object],\n        freeSockets: {},\n        keepAliveMsecs: 1000,\n        keepAlive: false,\n        maxSockets: Infinity,\n        maxFreeSockets: 256,\n        maxCachedSessions: 100,\n        _sessionCache: [Object] },\n     socketPath: undefined,\n     method: 'POST',\n     path: '/api/144447/store/',\n     _ended: false,\n     parser: \n      HTTPParser {\n        '0': [Function: parserOnHeaders],\n        '1': [Function: parserOnHeadersComplete],\n        '2': [Function: parserOnBody],\n        '3': [Function: parserOnMessageComplete],\n        '4': null,\n        _headers: [],\n        _url: '',\n        _consumed: false,\n        socket: [Object],\n        incoming: [Circular],\n        outgoing: [Circular],\n        maxHeaderPairs: 2000,\n        onIncoming: [Function: parserOnIncomingClient] },\n     res: [Circular] } }\n"}

**Comment by luxas** [comment]
I've come across this too.

**Comment by manooll** [comment]
Same error here. On FC26
