### ISSUE TITLE
Error sending Email - IMAP mappings? 

### ISSUE THREAD

**Issue by nicholasbutlin** [nylas/nylas-mail#3616]
##### Are there any related issues?
Probably 
#3222 , #3212, #3428

##### What operating system are you using?
ubuntu 16.04 

##### What version of Nylas Mail are you using?
2.0.32

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None 

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Only gmail accounts 

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No it happens to all sent messages 

Error Popup:
Your message successfully sent; however, we had trouble saving your message, "Test", to your Sent folder.
Could not find folder with role 'trash'.

Clicking on "Show Details" doesn't display anything.

Although it does actually show in the sent folder, just that every email sent pops this message up.

**Comment by nicholasbutlin** [comment]
Apologies - just found the fix!

**Comment by nicholasbutlin** [comment]
Reopening as I get a message saying the tarash cannot be set on Gmail: 


Details: 
Error
    at new APIError (/src/flux/errors.es6:57:19)
    at Request.<anonymous> (/src/flux/nylas-api-request.es6:89:30)
    at emitNone (events.js:86:13)
    at Request.emit (events.js:185:7)
    at Request.abort (/usr/share/nylas-mail/resources/app.asar/node_modules/request/request.js:1096:8)
    at ClientRequest.<anonymous> (/usr/share/nylas-mail/resources/app.asar/node_modules/request/request.js:777:16)
    at ClientRequest.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at ClientRequest.emit (events.js:185:7)
    at Socket.emitTimeout (_http_client.js:614:10)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:334:8)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
